version: "3.7"

services:
  aws-cli:
    container_name: aws-cli
    image: amazon/aws-cli
    stdin_open: true
    tty: true
    env_file:
      - .aws-env
    volumes:
      - "./named_profiles:/root/.aws"
