version: "3.7"
services:
  db:
    container_name: postgres_db
    image: postgres:12.2
    restart: always
    env_file:
      - .pg-env
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./assets:/assets"
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    container_name: pgadmin_gui
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - .pgadmin-env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgnetwork

volumes:
  db-data:
  pgadmin-data:

networks:
  pgnetwork:
