version: "3.7"
services:
  db:
    image: postgres:12.2
    restart: always
    env_file:
      - .pg-env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - .pgadmin-env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    hostname: pgadmin4
    networks:
      - pgnetwork

volumes:
  db-data:
  pgadmin-data:

networks:
  pgnetwork:
